---

- name: prepare
  ansible.builtin.import_tasks: prepare.yaml
  become: true
  tags:
    - senchacmd_prepare

# - name: download
#   ansible.builtin.include_tasks: download.yaml
#   when:
#     - not stat_senchacmd_binary.stat.exists
#
# - name: install
#   ansible.builtin.import_tasks: install.yaml
#   become: true
#   tags:
#     - senchacmd_install

...
