---
- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: arch- / artixlinux
      when:
        - ansible_distribution | lower == 'archlinux' or
          ansible_os_family | lower == 'artix linux'
      block:
        - name: update pacman system
          command: |
            pacman --refresh --sync --sysupgrade --noconfirm

        - name: define java_packages
          set_fact:
            java_packages:
              - jdk11-openjdk

        - name: Ensure Java is installed.
          package:
            name: "{{ java_packages + ['freetype2', 'fontconfig', 'ttf-terminus-nerd'] }}"
            state: present

    - name: debian / ubuntu
      when:
        - ansible_os_family == 'Debian'
      block:
        - name: define java_packages
          set_fact:
            java_packages:
              - openjdk-11-jdk

    - name: update package cache
      become: true
      ansible.builtin.package:
        update_cache: true

  roles:
    - role: java
      when:
        - not ansible_distribution | lower == 'archlinux'
